name: PR Workflow

on:
  pull_request:
    branches: [development, release-*]

permissions:
  contents: read
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run_tests:
    # Temporary. This branch with the fix is based on ai-dial-ci version 4.7.0
    uses: epam/ai-dial-ci/.github/workflows/node_pr.yml@feat/ort-allow-dynamic-versions-report-formats
    with:
      ort-allow-dynamic-versions: "false" # feat branch only
      ort-report-formats: "CycloneDx,SpdxDocument" # feat branch only
      node-version: "24"
    secrets: inherit
