name: Release Workflow

on:
  push:
    branches: [development, release-*]

permissions:
  contents: write
  packages: write
  security-events: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    # Temporary. This branch with the fix is based on ai-dial-ci version 4.7.0
    uses: epam/ai-dial-ci/.github/workflows/node_release.yml@feat/ort-allow-dynamic-versions-report-formats
    with:
      ort-allow-dynamic-versions: "false" # feat branch only
      ort-report-formats: "CycloneDx,SpdxDocument" # feat branch only
      promote: true
      publish-enabled: false
      draft-stable-releases: true
      node-version: "24"
    secrets: inherit
